### ISSUE TITLE
Error in Install instructions

### ISSUE THREAD

**Issue by bkm888** [kid1194/frappe-active-users#1]
In step #3 of the install instructions it reads:

`bench build --apps active_users`

However, it should read as follows:

`bench build --app active_users`

The switch --app is not plural

~BKM

**Comment by kid1194** [comment]
@bkm888 Thanks for your report..
In frappe docs it is stated as `bench build --apps [App Name]`
[https://frappeframework.com/docs/v14/user/en/basics/asset-bundling](Asset Bundling) 

So, are you sure that `--apps` is not the right build option?

**Comment by bkm888** [comment]
_So, are you sure that --apps is not the right build option?_

Yes. I am sure. I tried following your instructions by using the cut and paste method right from your published instructions. When the command uses '--apps' it returns an error indicating that --apps is not a valid switch.

If you delete the 's' then the command works.

Regardless of what the official ERPNext/Frappe documentation may have published, the instructions, as published, will not work.

Hope this helps.

~BKM

**Comment by kid1194** [comment]
@bkm888 Thanks a lot for your confirmation..
