### ISSUE TITLE
Attribute Error being generated every minute after install

### ISSUE THREAD

**Issue by bkm888** [kid1194/frappe-active-users#2]
My system:

ERPNext : v13.11.1
Frappe:     v13.11.0

Running on a Ubuntu 20.04 LTS VPS (KVM virtualization) server with 4gb RAM, 4 CPU, 4gb Swap, 60GB SSD main drive

After installing the active_users application my system started generating the following error every minute:
(Note: my refresh frequency is also set to one minute, but that may or may not be relevant)

`AttributeError: 'str' object has no attribute 'nodes_' `

This only 'appears' to be happening to users with the roles that are defined in the Active Users Settings although my limited testing ability cannot tie that statement down as a unique positive. There may also be others conditions where the error is popping up.

However, when it does pop up it stops all other system UI processing. It looks like this on the screen:

  
![Active_Users](https://user-images.githubusercontent.com/30693364/192149918-70bd1516-a34a-4027-9d66-1f8042a56fd1.jpg)

Additionally, I have never been able to access the Active Users list through the icon at the top of the screen. It only generates a rotating set of squares GIF that lasts until the next iteration of the AttributeError above and then drops out. It looks like this:

![Active_Users_Display](https://user-images.githubusercontent.com/30693364/192150132-003882f0-a3af-4cc0-9160-fa51e0773894.jpg)

If I can come up with any more data to be of help, I will post again.

~BKM

**Comment by kid1194** [comment]
@bkm888 Thanks for your report..
This error is python related. I have updated the plugin so please update and check if the same error still pops up..

**Comment by bkm888** [comment]
Wow, okay. Thanks for the fast reply. I did not expect anyone to reply today on Sunday so I tore down my server and started the rebuild process to get it back into testing condition.

It will still be another 2 hours before it is ready to go back to testing mode again. I have to restore a 7gb database to it first.

May have to wait until tomorrow to get back to testing your app (but I absolutely will finish testing it). So that means I will be starting over with the install of the app as well.

~BKM

**Comment by kid1194** [comment]
@bkm888 I apologize for what you had to go through..
I will be waiting for your reply..
And I'm very thankful for your help..

**Comment by kid1194** [comment]
@bkm888 Where you able to try the latest update? I want to know if the problem still exists of not..

**Comment by kid1194** [comment]
This issue will be considered as resolved since @bkm888 didn't confirm the issue status in the latest update..
