### ISSUE TITLE
Unable to get the list of active users.

### ISSUE THREAD

**Issue by Govind-Jangid** [kid1194/frappe-active-users#4]

**Comment by kid1194** [comment]
@Govind-Jangid Thank you for your comment and I'm sorry that this is happening to you.

I have updated the plugin recently to v1.0.3 and fixed the problem so please check if you are using the v1.0.3 or an earlier version and then please let me know what version you are using so I can fix the problem.

FYI: v1.0.3 has not been approved yet in Frappe Cloud.

**Comment by kid1194** [comment]
This issue will be considered as resolved since @Govind-Jangid  didn't confirm the issue status in the latest update..
