### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iMoshi** [kid1194/frappe-active-users#6]
I got the following error when installing :) 

On Frappe v14

```
File "apps/active_users/active_users/active_users/doctype/active_users_settings/active_users_settings.py", line 20
        def before_save(self):
    ^
TabError: inconsistent use of tabs and spaces in indentation
```

I did small changes, and proceeded, then I got this:

`ImportError: Module import failed for Active Users Has Role, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.active_users_has_role'`

**Comment by kid1194** [comment]
@iMoshi Thanks a lot for reporting this bug..
I have updated the plugin so please update and let me know if the problem is still there..

**Comment by iMoshi** [comment]
It keeps saying `No module named 'frappe.core.doctype.active_users_has_role'` for some reason. I'm on v14 btw :)

**Comment by kid1194** [comment]
@iMoshi After a lot of digging, I didn't find any problem with the plugin so I think that this error is a bug in your current version of python or bench..

No one has reported such error before..

**Comment by iMoshi** [comment]
> @iMoshi After a lot of digging, I didn't find any problem with the plugin so I think that this error is a bug in your current version of python or bench..
> 
> No one has reported such error before..

I've just created a new-site in my bench, git fetch and git pull the latest of this app, and tried installing it on the that new site. Same error. 

Then I uninstalled the app, removed references from my apps.txt / .json, removed the app, and finally re-installed. This time it just went through.

Thank you!

**Comment by kid1194** [comment]
@iMoshi It's great to hear that it worked for you..
Thanks a lot for trying 😁
