### ISSUE TITLE
What if there are 30 active users online?

### ISSUE THREAD

**Issue by robert1112** [kid1194/frappe-active-users#7]
Hello TEAM,

I just found this and really like being able to check who is online. 

1. I wonder if there are many active users like more than 30. How do you solve this?
2. What is regarded ACTIVE? Not logged out or mouse moving in at least 10 mins? 

Thank you for such interesting plugin.

**Comment by kid1194** [comment]
@robert1112 Thank you a lot for reaching out..

Let me explain to you how this plugin checks for active users..

There are two fields in system settings called `Session Expiry` and `Mobile Session Expiry` which stores the time that it takes for a login session to expire..

- First the plugin gets the `Session Expiry` if it's set, gets `Mobile Session Expiry` as a fallback if it's set and the first isn't. If none of these two fields is set, the it considers the session expiry time as 20 minutes..

- Second, it deducts the session expiry time from the current actual time. Ex: If current time is 18:25:40 and session expiry time is 20 minutes, then the result becomes 18:05:40..

- Third, it checks the users table for the active users by checking if the user is enabled, if the user type is one of the selected user type in the plugin settings and finally it checks if the last active time of the user is greater or equal the result time from the second part. If all these 3 checks are true, then the user is considered active..

I hope that I have made everything clear for you. 

If you still have some questions, please feel free to ask..

Best regards..

**Comment by robert1112** [comment]
Hi @kid1194 Thanks so much for such detail which is exactly I am looking for.

Here are a few follow-up questions:

Do you mean the plugin will also check user's activity log like login, logout, session expired, etc. Does it detect activity like view, open or edit? Because I have 06:00 for both Session Expiry and Mobile Session Expiry.  I consider It is a bit long to judge whether or not the users are still using. 

And how are you going to deal with like 30 users online? Thank you so mucj.

**Comment by kid1194** [comment]
> Do you mean the plugin will also check user's activity log like login, logout, session expired, etc.

It doesn't check any logs. It just checks the last active field from the `User` doctype to check if the user is active or not. Frappe updates this field whenever the user do anything while logged in.

> Does it detect activity like view, open or edit?

No it doesn't.

> Because I have 06:00 for both Session Expiry and Mobile Session Expiry. I consider It is a bit long to judge whether or not the users are still using.

Six hours is very long. Try to keep the session expiry time below 30 minutes for better security, since long living sessions can be hijacked and used to gain access to the system.

> And how are you going to deal with like 30 users online?

The load on the server depends on the refresh interval that can be set in the plugin's settings and the number of active users. 30 active users will not cause any problem.

The plugin uses JavaScript to refresh the list of active users depending on the interval. The list isn't cached since the list is changeable. The refresh can happen more frequent than intended if the user go to another page during the refresh idle time.

In terms of displaying a big list of active users, the list container has a maximum height so it doesn't expand that much and the list can be scrolled to accommodate more than 30 users.

**Comment by kid1194** [comment]
@robert1112 I have updated the plugin so please give it a try..

Now the plugin will cache the list of active users if the refresh interval is set to 10 minutes or more..

**Comment by kid1194** [comment]
@robert1112 Can you please confirm the status of the latest update if you installed the plugin?

If everything is ok, then I will push the latest version to the marketplace..

Best regards..

**Comment by robert1112** [comment]
@kid1194 Hi Sorry for the late reply. I dont see the notification from github until I check the repo by myself. I will feedback soon. Thank you.

**Comment by robert1112** [comment]
> > Do you mean the plugin will also check user's activity log like login, logout, session expired, etc.
> 
> It doesn't check any logs. It just checks the last active field from the `User` doctype to check if the user is active or not. Frappe updates this field whenever the user do anything while logged in.
> 
> > Does it detect activity like view, open or edit?
> 
> No it doesn't.
> 
> > Because I have 06:00 for both Session Expiry and Mobile Session Expiry. I consider It is a bit long to judge whether or not the users are still using.
> 
> Six hours is very long. Try to keep the session expiry time below 30 minutes for better security, since long living sessions can be hijacked and used to gain access to the system.
> 
> > And how are you going to deal with like 30 users online?
> 
> The load on the server depends on the refresh interval that can be set in the plugin's settings and the number of active users. 30 active users will not cause any problem.
> 
> The plugin uses JavaScript to refresh the list of active users depending on the interval. The list isn't cached since the list is changeable. The refresh can happen more frequent than intended if the user go to another page during the refresh idle time.
> 
> In terms of displaying a big list of active users, the list container has a maximum height so it doesn't expand that much and the list can be scrolled to accommodate more than 30 users.

Thanks so much for such detail. I looked like a very carefully designed and well-thought-out plugin. 👍

**Comment by kid1194** [comment]
@robert1112 Thanks a lot buddy..

I will be patiently waiting for your feedback..

Best regards..

**Comment by robert1112** [comment]
I seems working good. But I noticed a cosmetic issue on dark theme though? Thank you such nice plugin.
[https://share.cleanshot.com/gnCZfHCD](url)

**Comment by kid1194** [comment]
@robert1112 Can you please provide a screenshot?

That will help a lot..

I'm glad that you found it nice 😀

**Comment by kid1194** [comment]
@robert1112 I managed to see your screenshot and I have updated the style for dark theme 😀

Thanks a lot buddy for your help..

Best regards..
