### ISSUE TITLE
[BUG] error on install

### ISSUE THREAD

**Issue by RJPvT** [kid1194/frappe-active-users#8]
Hi! 

I'm getting the following on install 👍 
btw the plugin is working fine even with the error

Compiling Python files...
*** Error compiling '/home/frappe/frappe-bench/apps/active_users/active_users/setup/install.py'...
  File "/home/frappe/frappe-bench/apps/active_users/active_users/setup/install.py", line 22
    if (roles := frappe.db.get_list(
              ^
SyntaxError: invalid syntax

*** Error compiling '/home/frappe/frappe-bench/apps/active_users/active_users/setup/migrate.py'...
  File "/home/frappe/frappe-bench/apps/active_users/active_users/setup/migrate.py", line 16
    if (managers := get_system_managers(only_name=True)):
                 ^
SyntaxError: invalid syntax

**Comment by kid1194** [comment]
@RJPvT Thank you so much for reporting this..

There is no syntax error in the code so maybe it is because of having an old python or bench version..

Anyway, I have changed the syntax that is causing this error. I have used a simple syntax.

Best regards..

**Comment by RJPvT** [comment]
Thanks. This is solved :-)

You can close.

**Comment by kid1194** [comment]
@RJPvT Thanks a lot buddy for your response. 

Best regards..
